name: Publish to Github Package

on:
  push:
    branches:
      - release/*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: make gradlew executable
        run: chmod +x gradlew

      - name: Publish package
        run: ./gradlew sonatypeCentralUpload
        env:
          SONATYPE_CENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_CENTRAL_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_SIGNING_KEY: ${{ secrets.PGP_SIGNING_KEY }}
          PGP_SIGNING_KEY_PASSPHRASE: ${{ secrets.PGP_KEY_PASSPHRASE }}
